### ISSUE TITLE
Public the dog weights gdrive link 

### ISSUE THREAD

**Issue by ucalyptus2** [sanghunpark/neural_crossbreed#6]
This link is private -> https://drive.google.com/drive/folders/1IhxQ-fus-maSEakuFy7PorP1dkWI1WyR?usp=sharing

**Comment by ucalyptus2** [comment]
cc : @sanghunpark

**Comment by sanghunpark** [comment]
@forkbabu 
I think we shared the checkpoint file with the right privacy settings.
Can you try 'gdown command' in a terminal?
[https://github.com/wkentaro/gdown](url)

`pip install gdown`
`gdown https://drive.google.com/uc?id=1Z2n-KT2VFgRvhE5BYDg4Tsbeq-Eaq8_L`

**Comment by sanghunpark** [comment]
If the issue persists, please don't hesitate to reopen it again.
